# Generated by Django 4.2.27 on 2025-12-16 11:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.TextField()),
                ('image_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('PASS', 'Pass'), ('BLOCK', 'Block'), ('ERROR', 'Error')], default='QUEUED', max_length=20)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('scores', models.JSONField(blank=True, default=dict)),
                ('result_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
